name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print greeting
        run: |
          echo "Hello friend"
          echo "This is another line"
          echo "And another one"

      - name: Print goodbye
        run: |
          echo "Bye!"
          echo "See you later"
